FROM python:3.9-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY python-core/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY python-core ./python-core
WORKDIR /app/python-core
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
